[project]
name = "sandbox"
version = "0.1.0"
description = "sandbox using crewAI"
authors = [{ name = "Your Name", email = "you@example.com" }]
requires-python = ">=3.10,<3.13"
dependencies = [
    "crewai[tools]>=0.121.0,<1.0.0"
]

[project.scripts]
sandbox = "sandbox.main:run"
run_crew = "sandbox.main:run"
train = "sandbox.main:train"
replay = "sandbox.main:replay"
test = "sandbox.main:test"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.crewai]
type = "crew"
